name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['4.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install

      - name: Create basic test
        run: |
          echo 'module.exports = { testFunction: () => true };' > index.js
          echo 'const { testFunction } = require("./index.js"); test("Simple test", () => { expect(testFunction()).toBe(true); });' > index.test.js
          echo '{"scripts":{"test":"jest"},"dependencies":{},"devDependencies":{"jest":"^29.7.0"}}' > package.json
          chmod +x node_modules/.bin/jest
      
      - name: Run tests
        run: npx jest

      
